data_guest: "../../data/give_credit_hetero_guest.csv"
data_host: "../../data/give_credit_hetero_host.csv"
idx: "id"
label_name: "y"
penalty: "L2"
max_iter: 30
alpha: 10
learning_rate: 0.15
optimizer: "rmsprop"
batch_size: -1
early_stop: "diff"
init_method: "zeros"