data_guest: "examples/data/give_credit_hetero_guest.csv"
data_host: "examples/data/give_credit_hetero_host.csv"
idx: "id"
label_name: "y"
penalty: "L2"
max_iter: 6
alpha: 10
learning_rate: 0.2
optimizer: "adam"
batch_size: 5500
early_stop: "diff"
init_method: "zeros"