data_guest: "examples/data/vehicle_scale_hetero_guest.csv"
data_host: "examples/data/vehicle_scale_hetero_host.csv"
idx: "id"
label_name: "y"
penalty: "L2"
max_iter: 50
alpha: 0.0001
learning_rate: 0.15
optimizer: "adam"
batch_size: 16
early_stop: "diff"
init_method: "zeros"