sudo: required

cache:
  directories:
    - $HOME/.ccache
notifications:
  slack:
    on_success: never
    on_failure : never

matrix:
  include:
    - env: OS='centos:7'

  include:
    - language: python
      python: 3.6

install:
  - pip install codecov

script:
  - wget https://webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com/standalone-fate-master-1.5.0_preview.tar.gz
  - tar -xzf  standalone-fate-master-1.5.0_preview.tar.gz
  - cd standalone-fate-master-1.5.0_preview
  - sed -i.bak "s/sh  service.sh/bash service.sh/g" init.sh
  - sh init.sh init
  - ls -alh
  - source bin/init_env.sh
  - bash ./python/federatedml/test/run_test.sh
after_success:
  - conda install -c conda-forge codecov --yes
  - cd ./python/federatedml/test && codecov


