train_auc: 0.975186
api_version: v1
component_name: hetero_lr_0
metric_output_path: ./output/metric/{}_hetero_lr_0.json
model_output_path: ./output/model/{}_hetero_lr_0.json
phone_num: 12345678900

flow_test_template:
  train_conf_path: /examples/flow_test_template/hetero_lr/hetero_lr_normal_conf.json
  train_dsl_path: /examples/flow_test_template/hetero_lr/hetero_lr_normal_dsl.json
  predict_conf_path: /examples/flow_test_template/hetero_lr/hetero-lr-normal-predict-conf.json
  predict_dsl_path: /examples/flow_test_template/hetero_lr/hetero-lr-normal-predict-dsl.json
  upload_conf_path: /examples/flow_test_template/hetero_lr/upload_conf.json
  model_conf_path: /examples/flow_test_template/hetero_lr/model_conf.json
