data_guest: "/home/cwj/FATE/standalone-fate-master-1.4.5/examples/data/vehicle_scale_homo_guest.csv"
data_host: "/home/cwj/FATE/standalone-fate-master-1.4.5/examples/data/vehicle_scale_homo_host.csv"
data_test: "/home/cwj/FATE/standalone-fate-master-1.4.5/examples/data/vehicle_scale_homo_test.csv"
idx: "id"
label_name: "y"
