parties: # parties default id
  guest:
    - 10000
  host:
    - 9999
    - 10000
  arbiter:
    - 9999

backend: 0 # 0 for eggroll, or 1 for spark

work_mode: 0 # 0 for standalone, or 1 for cluster

data_base: "/data/projects/fate" # path to project base where data is located